# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  identifier = "home"
  name = "Home"
  url = "#"
  weight = 10

# [[main]]
#  name = "Projects"
#  url = "project/"
#  weight = 20

[[main]]
  identifier = "projects"
  name = "Projects"
  url = "projects/"
  weight = 30

[[main]]
  identifier = "publications"
  name = "Publications"
  url = "publication/"
  parent="projects"
  weight = 1

[[main]]
  identifier = "talk"
  name = "Talks and Tutorials"
  url = "talk/"
  parent="projects"  
  weight = 2

[[main]]
  identifier = "careers"
  name = "Careers"
  url = "careers/"
  weight = 60

[[main]]
  identifier = "news"
  name = "News and Media"
  url = "/news"
  weight = 70

[[main]]
  identifier = "team"
  name = "Team"
  url = "/team"
  weight = 80

[[main]]
  identifier = "grants"
  name = "Grants and Funding"
  url = "#grants"
  weight = 90

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "#contact"
  weight = 100

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
